DROP TABLE IF EXISTS authors_organisations;
DROP TABLE IF EXISTS papers_venues;
DROP TABLE IF EXISTS papers_publishers;
DROP TABLE IF EXISTS papers_authors;
DROP TABLE IF EXISTS organisations;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS publishers;
DROP TABLE IF EXISTS venues;
DROP TABLE IF EXISTS papers;
